site_name: Comunidade Sustentável API
site_description: Documentação da API de Comunidades Sustentáveis
site_author: Equipe de Desenvolvimento

theme:
  name: material
  palette:
    primary: green
    accent: light green
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - API:
    - Endpoints: api/endpoints.md
    - Modelos: api/models.md
  - Guias:
    - Instalação: guias/instalacao.md
    - Desenvolvimento: guias/desenvolvimento.md
    - Testes: guias/testes.md
    - Hospedagem: guias/hospedagem.md
